authcontr/accounts/urls.py
from django.conf.urls import url,include
from . import views



urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    # url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$',views.ProfileView.as_view(),name='profile_view'),
]

#
# from account import views as user_views
# from django.contrib.auth import views as auth_views
#
# urlpatterns = [
#     url(r'^signup/$',user_views.SignUp.as_view(),name='signup'),
#     url(r'^login/$',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
#     url(r'^logout/$', auth_views.LogoutView.as_view(template_name='account/logout.html'),name='logout'),
#     url(r'^profile/$',user_views.ProfileView.as_view(),name='profile_view'),
#     url(r'^update/profile/$',user_views.ProfileUpdate.as_view(),name='profile_update'),
#     # urls for password change
#     url(r'^change-password/$',user_views.MyPasswordChangeView.as_view(template_name='account/change-password.html'),
#                 name='change_password'),
#     # urls for password reset
#
# ]

authcontr/authcontr/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views import generic
from accounts import urls as user_urls
from accounts.views import activate  #,signup

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',generic.TemplateView.as_view(template_name='layout.html'),name='home'),
    url(r'^accounts/',include(user_urls,namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

authcontr/templates/_extentions/_nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Win</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#na" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="na">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout'%}">Log Out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login'%}">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
      </li>
      {% endif %}

      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>